### PR TITLE
Keep the email address

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
no need to re-enter between tests

minor convenience, it saves me from having to enter a test email address repeatedly

### CODE REVIEW

**Comment by harrison-broadbent** [comment]
thanks for putting this together! I might just need a day or two to get around to testing and merging this.

**Comment by ConfusedVorlon** [comment]
ping...

**Comment by harrison-broadbent** [comment]
gah sorry

**Comment by ConfusedVorlon** [comment]
no worries - we all have day jobs ;)

**Comment by harrison-broadbent** [comment]
Sorry this took so long. Looks great! I'll merge now and roll `v1.0.3` shortly (I want to include a ruby + deps bump)

**Review by harrison-broadbent — APPROVED** [review]
👏

**Pull request merged**
